name: docker-build

on:
  push:
    branches:
      - "latessa/dockerImage"

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_DRAFT_USERNAME }}
          password: ${{ secrets.DOCKER_DRAFT_PAT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile_root6-18-04_hepmc3-1-1.base
          push: true
          tags: ${{ secrets.DOCKER_DRAFT_USERNAME }}/jetscap:v1.7.1_beta