name: docker-build

on:
  push:
    branches:
      - "latessa/dockerImage"

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_DRAFT_USERNAME }}
          password: ${{ secrets.DOCKER_DRAFT_PAT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${GITHUB_WORKSPACE}/${REPO_NAME}
          file: {context}/Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKER_DRAFT_USERNAME }}/jetscap:v1.8_beta